### PR TITLE
docs: Update Security Command Center UpdateNotificationConfig sample, adding filter to mutable field

### PR DESCRIPTION
**Pull request by hannah-tsai**
Fixes b/155346619
Add "filter" to mutable fields for UpdateNotificationConfig.

### CODE REVIEW

**Comment by hannah-tsai** [comment]
Hi,
Not sure why the Kokoro checks didn't seem to finish, any idea on how to restart or resolve this?

**Comment by busunkim96** [comment]
@hannah-tsai The CI won't run unless you are a member of an org. Someone with write access needs to nudge it by adding a label.

**Comment by hannah-tsai** [comment]
Hi, not sure if I should be concerned with the Kokoro build failure?

**Comment by busunkim96** [comment]
Hi @hannah-tsai,

Would you mind modifying this PR to change [this file](https://github.com/googleapis/python-securitycenter/blob/master/samples/snippets/snippets_notification_configs.py) instead? I shuffled the snippets into a different directory in #41.

**Comment by hannah-tsai** [comment]
Updated change list, busunkim96@ could you help to add a label to start the Kokoro test? Thanks!

**Pull request merged**
